# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'ARINTO HADI WIHARYO'
tagline:          'just try'
description:      'awesome as always'
url:              http://arintole.github.io/
baseurl:          /

author:
  name:           'Arinto Hadi Wiharyo'
  url:            https://twitter.com/arintole

paginate:         4

# Custom vars      

github:
  repo:           https://github.com/arintole/arintole.github.io

socialmedia: 
  twitter:        https://twitter.com/arintole
  linkedin:       https://www.linkedin.com/in/arintohadiwiharyo